version: "3.8"

services:
  newsapp:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - "REACT_APP_API_KEY=${REACT_APP_API_KEY}"
      - "REACT_APP_PROXY_URL=${REACT_APP_PROXY_URL}"
